### ISSUE TITLE
Consume current golang-version

### ISSUE THREAD

**Issue by joergdw** [cloudfoundry/bpm-release#154]
The current release is not up-to-date. However the golang-versions prior to 1.18.2 and 1.17.10 have [CWE 284](https://cwe.mitre.org/data/definitions/284.html). Could you publish soon the next release to fix this, please?

**Comment by beyhan** [comment]
@jpalermo do you know when we will have a new release?

**Comment by jpalermo** [comment]
We don't cut them on a schedule, and try not to cut them too frequently as an update to `bpm` means every VM has to be updated which frustrates users with large deployments. I don't think this CVE actually impacts `bpm`, but I went ahead and cut 1.1.18 because that's much easier than proving it's not impacted 😀

**Comment by beyhan** [comment]
Thank you @jpalermo!
